import "./globals.css";
import { Montserrat } from "next/font/google";
import Link from "next/link";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "The Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`${montserrat.className} mx-12 sm:mx-32`}>
        <nav className=" text-center mt-10 ">
          <Link href="/">
            <div className="p-3 border-2 border-white rounded-xl inline-block font-bold sm:text-4xl text-sm text-white">
              The Movie App
            </div>
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
